spring.application.name=demo

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ApiRestChallengeAlura9Marzo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=usuario_crud
spring.datasource.password=Brunobruno.12=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# Configuración del servidor
server.port=8085
server.servlet.context-path=/api

# Configuración JWT
app.jwtSecret=aB9$kL2#mN5@pQ8!rS4%tU7^vW6&xY3*zC0(dE1)fG+hI-jK=lM
app.jwtExpirationMs=86400000

# Configuración de Logging
logging.level.root=INFO
logging.level.AndersonC15=DEBUG